### ISSUE TITLE
Test Code Scanning

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/bivittatusDB#18]
@ScriptSlayer0 
I want to test some new code scanning workflows I've put in. Is there any way you can open a pull request early. We won't make it an official release just yet, just a test.

**Comment by ScriptSlayer0** [comment]
It works well, but only analyze the syntax using pylint.

**Comment by ScriptSlayer0** [comment]
I was working for a new PR, I created a new fork thinking it was my bad creating a new bug or error. But now I know it is this new version with compression and decompression problems and I need your help to get this software fixed and working again.

**Comment by HarbingerOfFire** [comment]
Can you let me know how to reproduce the issue? What file was used?

**Comment by ScriptSlayer0** [comment]
Only run the menu.py, choose option 2
```
info: Generating keys...Keys generated and saved.
Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\BDB_io.py", line 165, in ReadTable
    data = loads(decompress(unhexlify(data)).decode())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 46, in __read__
    self.data=self.io.ReadTable(self.table_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\BDB_io.py", line 169, in ReadTable
    raise metaclass.BDBException.ReadError(f"Error reading data from table {tablename}: {e}")
metaclass.BDBException.ReadError: Error reading data from table table1: Compressed file ended before the end-of-stream marker was reached
None
Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\BDB_io.py", line 165, in ReadTable
    data = loads(decompress(unhexlify(data)).decode())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 46, in __read__
    self.data=self.io.ReadTable(self.table_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\BDB_io.py", line 169, in ReadTable
    raise metaclass.BDBException.ReadError(f"Error reading data from table {tablename}: {e}")
metaclass.BDBException.ReadError: Error reading data from table table1: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\BivittatusDB.py", line 26, in load_table
    return table(self.db, self.database_name, table_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 24, in __init__
    self.__read__()
  File "D:\github\bivittatusDB\BivittatusDB\BDB_tb.py", line 50, in __read__
    raise BDBException.ReadError(f"Courld not read table {self.table_name}")
metaclass.BDBException.ReadError: Courld not read table table1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\github\bivittatusDB\BivittatusDB\menu.py", line 59, in <module>
    main_menu()
  File "D:\github\bivittatusDB\BivittatusDB\menu.py", line 52, in main_menu
    if not handle_option(option):
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\menu.py", line 40, in handle_option
    result = action()
             ^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\menu.py", line 31, in <lambda>
    "2": lambda: (pause_and_clean(0), add_names_to_db()),
                                      ^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\DB_manage\adding_rows.py", line 10, in add_names_to_db
    tb1 = test_db.New_table(
          ^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\BivittatusDB.py", line 53, in New_table
    return self.load_table(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bivittatusDB\BivittatusDB\BivittatusDB.py", line 28, in load_table
    raise metaclass.BDBException.IOError(f"Error finding table {table_name}")
metaclass.BDBException.IOError: Error find
```

**Comment by HarbingerOfFire** [comment]
I have found it's affecting all the example files as well. The error starts occuring in commits `660e151` (for WIN32) and `d586724` (for UNIX). It seems like our update in BivittatusDatabase was not as functional as expected.

**Comment by HarbingerOfFire** [comment]
It looks like we got control of the code scanning, so I'll go ahead and close this
